experiment: 00_protocol_calibration
name: unet_depth10_v0
task: segmentation
seed: 2025

data:
  train: data/new_validation/r1_r8_train_5sec.pkl
  valid: data/new_validation/r9_r10_val.pkl
  test: data/new_validation/r11_test.pkl
  train_dataset:
    module_name: benchmarks.data.segmentation
    class_name: TrainCroppingDataset
    params:
      sfreq: 100
      crop_sec: 2.0
      sigma: 0.15
      end_time: 3.0
      use_augmentation: true
      cropping_offset: 0.25
      crop_proba: 0.3
      dropout_proba: 0.25
      dropout_range: 0.25
  valid_dataset: null

loaders:
  train:
    batch_size: 2000
    shuffle: true
    num_workers: 8
  valid:
    batch_size: 256
    shuffle: false
    num_workers: 4

model:
  module_name: neurosned.models.segmentation.sneddy_unet
  class_name: SneddySegUNet1D
  params:
    n_chans: 128
    n_times: 200
    sfreq: 100
    c0: 128
    widen: 2
    depth_per_stage: 10
    dropout: 0.2
    k: 19
    out_channels: 1

optimizer:
  module_name: torch.optim
  class_name: Adam
  params:
    lr: 0.001
    weight_decay: 0

trainer:
  module_name: benchmarks.pkg.training.trainers
  class_name: SegmTrainer
  n_epochs: 10
  checkpoint:
    input: artefacts/models/challenge_1/unet_depth10_v0.pth
  monitor: nrmse
  minimize: true
  early_stopping_patience: 20
  print_batch_stats: true
  plateau:
    enabled: true
    factor: 0.5
  params:
    temperature: 0.65
    eval_temperature: 0.65
    lambda_time: 3.0
    eval_lambda_time: 1.0
    lambda_ce: 1.0
    lambda_kl: 0.0
    lambda_wass: 0.0
    lambda_entropy: 0.0
    lambda_focal: 0.0
    mixup_p: 0.1
    mixup_alpha: 0.4
    grad_accum: 1
    sigma: 0.15
    plot_last_batch: true
